COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://${{ secrets.MYSQL_ROOT_USER }}:${{ secrets.MYSQL_ROOT_PASSWORD }}@${{ secrets.ENDPOINT }}:3306/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://${{ secrets.MYSQL_ROOT_USER }}:${{ secrets.MYSQL_ROOT_PASSWORD }}@${{ secrets.ENDPOINT }}:3306/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: ${{ secrets.MYSQL_ROOT_USER }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
